Add deck detail page
onecrayon/ashes.live pull request #20
Opened 2021-01-17 17:16 UTC by FabienDeshayes

Adds the deck detail page, based on the static page I received.

Still to be done:
- export as text
- view history
- comments

Also I'm not 100% sure what can be expected as the input for the description so for now I've just copied what's done for the card text.
Feedback appreciated, I think the layout is still not perfect but still think it deserves a review.

Screenshots:
![image](https://user-images.githubusercontent.com/762494/104850538-a7276a80-58e7-11eb-8601-8f29a263e86d.png)
![image](https://user-images.githubusercontent.com/762494/104850550-af7fa580-58e7-11eb-8f06-2c83d76584b3.png)

2021-01-17 18:03 UTC, onecrayon requested changes
This is looking really good; just a few minor comments inline. Also, it looks like lists in descriptions are not styled with bullets by default, so we'll need either a generic class in `index.css` or a module class in the DeckDescription component.

2021-01-17 18:03 UTC, onecrayon commented on src/components/decks/DeckDetails.vue
> +<style scoped>
Let's stick to using `module` instead of `scoped` (ensures that styles don't affect child components). Note that modules require you to access the template name programmatically; e.g. `:class="$style.deckContainer"`.

2021-01-17 18:03 UTC, onecrayon commented on src/components/decks/DeckDetails.vue
> +      return this.deck.is_legacy ? `https://cdn.ashes.live/legacy/images/cards/${this.deck.phoenixborn.stub}-large.jpg` : `https://cdn.ashes.live/images/phoenixborn/${this.deck.phoenixborn.stub}.jpg`
Please refactor this into a shared utility function so that the string constants are only defined in a single component (could potentially allow setting a second parameter to specify if it should be big or small).

2021-01-17 18:03 UTC, onecrayon commented on src/components/decks/DeckDetails.vue
> +import { request, parseCardText } from '/src/utils.js'
This component doesn't appear to use `parseCardText`.

2021-01-17 18:03 UTC, onecrayon commented on src/components/decks/DeckDescription.vue
> +      parseCardText(props.content)
You'll need to specify all parameters for this to work properly (`ensureParagraphs` makes sure that if there's a single line it's properly wrapped in paragraph tags, and `isLegacy` affects whether embedded card links use legacy cards or Reborn cards).

2021-01-17 18:05 UTC, onecrayon commented
@FabienDeshayes Forgot to mention; the API stuff isn't in place for View History or Comments to function, so no need to worry about them for this PR.

2021-01-19 11:29 UTC, FabienDeshayes commented
Thanks for the feedback @onecrayon !
All comments should be addressed now. Anything on export as text? Or is it a bit early to have that?

2021-01-19 15:16 UTC, onecrayon commented
@FabienDeshayes Right, export as text. In the legacy site this was a hidden modal element on the deck view:

https://github.com/onecrayon/ashes.live-legacy/blob/503eec64163198d17f4bbe3265e64b403e2d747f/app/templates/decks/view.html#L97

However, it was based on a modal that allowed you to view a text version in the deck builder, so I’d like to have a shared component. Here’s the legacy component for reference/ ideas:

https://github.com/onecrayon/ashes.live-legacy/blob/master/app/static/src/app/deck_editor/export_modal.vue

2021-01-23 22:18 UTC, onecrayon approved these changes
@FabienDeshayes This is looking really good. I'm going to merge it in, and we can add the export functionality as its own PR.

2021-01-23 22:19 UTC, merged